spring:
  application:
    name: Event Management
  datasource:
    url: jdbc:mysql://localhost:3306/Event_Management_System?createDatabaseIfNotExist=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: codedrill
    password: Codedrill@237
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true

server:
  port: 8085

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
